# Structr Dashboard - Docker Compose for Development
version: '3.8'

services:
  structr-dashboard:
    build: .
    ports:
      - "8501:8501"
    environment:
      - PYTHONPATH=/app
      - STRUCTR_ENV=development
      - STRUCTR_OUTPUT_DIR=/app/output
      - STRUCTR_INPUT_DIR=/app/input
      - STRUCTR_LLM_MODEL=mistral
      - STRUCTR_SERVER_PORT=8501
    volumes:
      # Persist data directories
      - ./output:/app/output
      - ./input:/app/input
      - ./temp_uploads:/app/temp_uploads
      - ./cache:/app/cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for production job queuing
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    profiles: ["production"]

  # Optional: PostgreSQL for production data storage
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: structr
      POSTGRES_USER: structr
      POSTGRES_PASSWORD: structr_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    profiles: ["production"]

volumes:
  redis_data:
  postgres_data:

networks:
  default:
    driver: bridge