# Railway Deployment Configuration
[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/_stcore/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environment]
PYTHONPATH = "/app"
STREAMLIT_SERVER_PORT = "8501"
STREAMLIT_SERVER_ADDRESS = "0.0.0.0"
STREAMLIT_SERVER_HEADLESS = "true"
STREAMLIT_BROWSER_GATHER_USAGE_STATS = "false"
STRUCTR_ENV = "production"
STRUCTR_OUTPUT_DIR = "/app/output"
STRUCTR_INPUT_DIR = "/app/input"
STRUCTR_LLM_MODEL = "mistral"

[volume]
# Mount persistent storage for data
mountPath = "/app/data"
size = "10GB"